# Generated by Django 3.1.1 on 2020-09-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddU2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('fn', models.CharField(max_length=50)),
                ('ln', models.CharField(max_length=50)),
                ('rno', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('br', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=50)),
                ('DD', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'AddU2',
            },
        ),
        migrations.CreateModel(
            name='Assgin2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=50)),
                ('dd', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('stream', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=50)),
                ('picture', models.FileField(upload_to='pdf')),
            ],
            options={
                'db_table': 'Assgin2',
            },
        ),
        migrations.CreateModel(
            name='Attend1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=50)),
                ('sub', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Attend1',
            },
        ),
        migrations.CreateModel(
            name='Compbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com', models.CharField(max_length=60)),
                ('co', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Compbox',
            },
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('na', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=50)),
                ('message', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Contactus',
            },
        ),
        migrations.CreateModel(
            name='EditA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.CharField(max_length=50)),
                ('sub', models.CharField(max_length=50)),
                ('Alec', models.CharField(max_length=50)),
                ('Dlec', models.CharField(max_length=50)),
                ('per', models.CharField(max_length=50)),
                ('dd', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'EditA',
            },
        ),
        migrations.CreateModel(
            name='eventdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='pdf')),
            ],
            options={
                'db_table': 'eventdetails',
            },
        ),
        migrations.CreateModel(
            name='Internal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.CharField(max_length=50)),
                ('sub', models.CharField(max_length=50)),
                ('mst1', models.CharField(max_length=50)),
                ('mst2', models.CharField(max_length=50)),
                ('assgin1', models.CharField(max_length=50)),
                ('assgin2', models.CharField(max_length=50)),
                ('attend', models.CharField(max_length=50)),
                ('internal', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Internal',
            },
        ),
        migrations.CreateModel(
            name='KStudent2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('op', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='marks1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.CharField(max_length=50)),
                ('ex', models.CharField(max_length=50)),
                ('br', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=50)),
                ('sub', models.CharField(max_length=50)),
                ('max', models.CharField(max_length=50)),
                ('mo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'marks1',
            },
        ),
        migrations.CreateModel(
            name='marks2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.CharField(max_length=50)),
                ('ex', models.CharField(max_length=50)),
                ('br', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=50)),
                ('sub', models.CharField(max_length=50)),
                ('max', models.CharField(max_length=50)),
                ('mo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'marks2',
            },
        ),
        migrations.CreateModel(
            name='Mst1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.CharField(max_length=50)),
                ('ex', models.CharField(max_length=50)),
                ('br', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=50)),
                ('sub', models.CharField(max_length=50)),
                ('max', models.CharField(max_length=50)),
                ('mo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Mst1',
            },
        ),
        migrations.CreateModel(
            name='Mst2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.CharField(max_length=50)),
                ('ex', models.CharField(max_length=50)),
                ('br', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=50)),
                ('sub', models.CharField(max_length=50)),
                ('max', models.CharField(max_length=50)),
                ('mo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Mst2',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('stream', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=50)),
                ('picture', models.FileField(upload_to='pdf')),
            ],
            options={
                'db_table': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='Notice1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='gallery')),
            ],
            options={
                'db_table': 'Notice1',
            },
        ),
        migrations.CreateModel(
            name='Profile1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('picture', models.FileField(upload_to='gallery')),
            ],
            options={
                'db_table': 'Profile1',
            },
        ),
        migrations.CreateModel(
            name='RegisterU2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('fn', models.CharField(max_length=50)),
                ('ln', models.CharField(max_length=50)),
                ('fathern', models.CharField(max_length=50)),
                ('collegename', models.CharField(max_length=50)),
                ('mno', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('br', models.CharField(max_length=50)),
                ('eventcategory', models.CharField(max_length=50)),
                ('eventname', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=50)),
                ('DD', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'RegisterU2',
            },
        ),
        migrations.CreateModel(
            name='STime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=50)),
                ('picture', models.FileField(upload_to='gallery')),
            ],
            options={
                'db_table': 'STime',
            },
        ),
        migrations.CreateModel(
            name='Subject1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('sub', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('fn', models.CharField(max_length=50)),
                ('ln', models.CharField(max_length=50)),
                ('ph', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('gen', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('userid', models.CharField(max_length=50)),
                ('picture', models.FileField(upload_to='gallery')),
            ],
            options={
                'db_table': 'Time',
            },
        ),
    ]
